# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1', models.IntegerField(default=3)),
                ('level2', models.IntegerField(default=3)),
                ('level3', models.IntegerField(default=3)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='subtopicid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quadraticsApp.SubTopicModel'),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='topicid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quadraticsApp.TopicModel'),
        ),
    ]
